const PHASES = {
  VIDEO_CONTEXT: 'VIDEO_CONTEXT', CONTEXT_COMPLETED: 'VIDEO_CONTEXT', CHUNKS_COMPLETED: 'RETRIEVAL', RETRIEVAL: 'RETRIEVAL',
  PLANNER: 'PLANNER', PLAN_COMPLETED: 'PLANNER', EXECUTOR: 'EXECUTOR', EXECUTOR_STARTED: 'EXECUTOR', EXECUTOR_COMPLETED: 'EXECUTOR',
  CRITIC: 'CRITIC', CRITIC_STARTED: 'CRITIC', CRITIC_PASSED: 'CRITIC', CRITIC_RETRY_REQUIRED: 'CRITIC', EVIDENCE_REFRESHED: 'CRITIC',
}

export function uiPhaseForStage(stage, lastKnown = null) {
  return Object.hasOwn(PHASES, stage) ? PHASES[stage] : lastKnown
}
