"""Adopt the frozen main schema, creating missing tables/compatible fields.

Historical unversioned installations use the same path as an empty database.
No runtime-model imports: this revision is a permanent schema snapshot.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = "0001_schema_baseline"
down_revision = None
branch_labels = None
depends_on = None


def _adopt_table(name, *parts, **kwargs):
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    if name not in inspector.get_table_names():
        op.create_table(name, *parts, **kwargs)
        return
    table = sa.Table(name, sa.MetaData(), *parts)
    existing = {column["name"]: column for column in inspector.get_columns(name)}
    populated = connection.execute(sa.select(sa.func.count()).select_from(sa.table(name))).scalar() > 0
    defaults = {
        ("agent_checkpoints", "stage"): "", ("users", "role"): "USER",
        ("failed_analysis_tasks", "mode"): "GENERAL",
        ("failed_analysis_tasks", "status"): "FAILED",
        ("agent_execution_records", "replayable"): False,
    }
    timestamps = {("agent_checkpoints", "updated_at"), ("media_files", "upload_time"),
                  ("failed_analysis_tasks", "created_at"), ("failed_analysis_tasks", "updated_at")}
    # Validate all changes before touching this legacy table. Identity/history
    # values cannot be safely guessed on populated tables.
    for column in table.columns:
        if column.name not in existing and populated and not column.nullable:
            if (name, column.name) not in defaults and (name, column.name) not in timestamps:
                raise RuntimeError(f"Unsupported legacy schema: missing required {name}.{column.name}; explicit data migration required")
    expected_pk = tuple(column.name for column in table.primary_key)
    if tuple(inspector.get_pk_constraint(name)["constrained_columns"]) != expected_pk:
        raise RuntimeError(f"Unsupported legacy primary key: {name}")
    for column in table.columns:
        if column.name in existing:
            continue
        # Add nullable, backfill safe historical defaults, then enforce NOT NULL.
        op.add_column(name, sa.Column(column.name, column.type, nullable=True))
        if not column.nullable:
            value = sa.func.current_timestamp() if (name, column.name) in timestamps else defaults.get((name, column.name))
            if populated:
                connection.execute(table.update().values({column.name: value}))
            with op.batch_alter_table(name) as batch:
                batch.alter_column(column.name, existing_type=column.type, nullable=False)
    uniques = {tuple(value["column_names"]) for value in sa.inspect(connection).get_unique_constraints(name)}
    foreign = {(tuple(value["constrained_columns"]), value["referred_table"], tuple(value["referred_columns"]))
               for value in sa.inspect(connection).get_foreign_keys(name)}
    for constraint in table.constraints:
        if isinstance(constraint, sa.UniqueConstraint):
            columns = tuple(column.name for column in constraint.columns)
            if columns not in uniques:
                with op.batch_alter_table(name) as batch:
                    batch.create_unique_constraint(constraint.name or f"uq_{name}_{'_'.join(columns)}", columns)
        elif isinstance(constraint, sa.ForeignKeyConstraint):
            elements = tuple(constraint.elements)
            columns = tuple(element.parent.name for element in elements)
            remote_table = elements[0].target_fullname.split('.')[0]
            remote_columns = tuple(element.target_fullname.split('.')[1] for element in elements)
            if (columns, remote_table, remote_columns) not in foreign:
                with op.batch_alter_table(name) as batch:
                    batch.create_foreign_key(constraint.name or f"fk_{name}_{remote_table}", remote_table,
                                             columns, remote_columns, ondelete=constraint.ondelete)


def _ensure_index(name, table_name, columns, **kwargs):
    indexes = {index["name"]: index for index in sa.inspect(op.get_bind()).get_indexes(table_name)}
    if name not in indexes:
        op.create_index(name, table_name, columns, **kwargs)
    elif tuple(indexes[name]["column_names"]) != tuple(columns) or bool(indexes[name]["unique"]) != bool(kwargs.get("unique", False)):
        raise RuntimeError(f"Legacy index conflicts with expected definition: {name}")


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    _adopt_table('agent_checkpoints',
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('checkpoint_key', sa.String(length=160), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('media_id', 'checkpoint_key')
    )
    _adopt_table('agent_execution_events',
    sa.Column('execution_id', sa.String(length=96), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('logical_event_id', sa.String(length=192), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('agent_round', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=96), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('execution_id', 'sequence_no'),
    sa.UniqueConstraint('execution_id', 'logical_event_id', name='uq_execution_event_logical_id')
    )
    _ensure_index('ix_execution_event_history', 'agent_execution_events', ['execution_id', 'sequence_no'], unique=False)
    _adopt_table('agent_execution_records',
    sa.Column('execution_id', sa.String(length=96), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('media_identity', sa.String(length=512), nullable=False),
    sa.Column('source_revision', sa.String(length=96), nullable=False),
    sa.Column('source_provenance_version', sa.String(length=96), nullable=False),
    sa.Column('mode_profile_version', sa.String(length=96), nullable=False),
    sa.Column('tool_policy_version', sa.String(length=96), nullable=False),
    sa.Column('record_schema_version', sa.String(length=96), nullable=False),
    sa.Column('execution_contract_version', sa.String(length=96), nullable=False),
    sa.Column('worker_attempt', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=96), nullable=True),
    sa.Column('parent_execution_id', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('replayable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    _ensure_index('ix_execution_record_task_history', 'agent_execution_records', ['media_id', 'goal', 'mode', 'created_at'], unique=False)
    _adopt_table('failed_analysis_tasks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('user_goal', sa.String(length=500), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _ensure_index(op.f('ix_failed_analysis_tasks_media_id'), 'failed_analysis_tasks', ['media_id'], unique=False)
    _adopt_table('media_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _ensure_index(op.f('ix_media_files_content_hash'), 'media_files', ['content_hash'], unique=False)
    _ensure_index(op.f('ix_media_files_user_id'), 'media_files', ['user_id'], unique=False)
    _adopt_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    _adopt_table('failed_analysis_task_replays',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('failed_task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['failed_task_id'], ['failed_analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('failed_task_id', 'idempotency_digest', name='uq_failed_task_replay_idempotency')
    )
    _ensure_index('ix_failed_task_replay_history', 'failed_analysis_task_replays', ['failed_task_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Legacy adoption is forward-only; restore a verified backup to roll back")
