"""Concrete, injectable real-provider adapters for Phase 10A.

No SDK or network call is imported/executed here.  An outer composition root
chooses a configured HTTP client (or deterministic fake) and wires these
adapters to the existing application ports.
"""

from .config import (
    EmbeddingProviderConfig,
    ModelRequestSettings,
    ModelProviderConfig,
    ProviderConfig,
    ProviderConfigurationError,
)
from .embedding import (
    EmbeddingAdapter,
    OpenAICompatibleEmbeddingAdapter,
    decode_embedding,
)
from .errors import (
    EmbeddingProviderError,
    EmbeddingResponseError,
    ModelProviderError,
    ModelResponseError,
    ProviderAuthenticationError,
    ProviderError,
    ProviderRequestError,
    ProviderResponseError,
    ProviderTransportError,
    ProviderTransientError,
)
from .http import (
    AsyncJsonPostClient,
    ProviderHttpResponse,
    StdlibAsyncJsonPostClient,
    post_json,
    response_parts,
)
from .local_embedding import LocalEmbeddingAdapter, LocalTfidfEmbeddingAdapter
from .model import (
    ChatCompletionPort,
    ChunkSummaryModelAdapter,
    CriticModelAdapter,
    DeepSeekModelAdapter,
    ExecutorModelAdapter,
    OpenAICompatibleChatClient,
    OpenAICompatibleChunkSummaryAdapter,
    OpenAICompatibleCriticAdapter,
    OpenAICompatibleExecutorAdapter,
    OpenAICompatibleModelAdapter,
    OpenAICompatiblePlannerAdapter,
    OpenAICompatibleRetrievalPlannerAdapter,
    PlannerModelAdapter,
    RetrievalPlannerModelAdapter,
    EXECUTOR_TOOL_AWARE_SYSTEM_POLICY,
    EXECUTOR_TOOL_TURN_CONTRACT,
    SYSTEM_POLICY,
    StructuredResponseObserver,
    STRUCTURED_RESPONSE_MAX_DIAGNOSTIC_BYTES,
    STRUCTURED_RESPONSE_MAX_ERRORS,
    STRUCTURED_RESPONSE_MAX_FIELDS,
    decode_structured_model,
)
from .summary import (
    DEFAULT_LOCAL_KEYWORDS,
    DEFAULT_LOCAL_SUMMARY_CHARS,
    LocalChunkSummaryAdapter,
    LocalSummaryAdapter,
)
from .mode_router import MODE_ROUTING_PROMPT, ModeRouterModelAdapter
from .jev import (
    JEV_DEFAULT_ENDPOINT,
    JEV_LANE_CRITERIA,
    JEV_LANE_INSTRUCTIONS,
    JEV_MAX_RESPONSE_COST_USD,
    JEV_QUESTION_KEY,
    OPENROUTER_DECISIONS_ENDPOINT,
    OPENROUTER_JEV_MODEL,
    JevAdapter,
    JevConfiguration,
    JevConfigurationError,
    JevModelRouter,
    JevModelRouterConfig,
    JevResponseError,
    JevRouterError,
    JevRouterObserver,
    JevRouterSettings,
    JevRouterUnavailableError,
    JevTransport,
    JevSystemOneModelRouter,
    TypeSafeModelRouter,
)
from .follow_up import (
    GroundedFollowUpModelAdapter,
    MAX_FOLLOW_UP_RESPONSE_CHARS,
    decode_follow_up_answer,
)

__all__ = [
    "AsyncJsonPostClient",
    "ChatCompletionPort",
    "ChunkSummaryModelAdapter",
    "CriticModelAdapter",
    "DEFAULT_LOCAL_KEYWORDS",
    "DEFAULT_LOCAL_SUMMARY_CHARS",
    "DeepSeekModelAdapter",
    "EmbeddingAdapter",
    "EmbeddingProviderConfig",
    "EmbeddingProviderError",
    "EmbeddingResponseError",
    "ExecutorModelAdapter",
    "EXECUTOR_TOOL_AWARE_SYSTEM_POLICY",
    "EXECUTOR_TOOL_TURN_CONTRACT",
    "LocalChunkSummaryAdapter",
    "LocalEmbeddingAdapter",
    "LocalTfidfEmbeddingAdapter",
    "LocalSummaryAdapter",
    "ModelProviderConfig",
    "ModelRequestSettings",
    "ModelProviderError",
    "MODE_ROUTING_PROMPT",
    "ModeRouterModelAdapter",
    "JEV_DEFAULT_ENDPOINT",
    "JEV_LANE_CRITERIA",
    "JEV_LANE_INSTRUCTIONS",
    "JEV_MAX_RESPONSE_COST_USD",
    "JEV_QUESTION_KEY",
    "OPENROUTER_DECISIONS_ENDPOINT",
    "OPENROUTER_JEV_MODEL",
    "JevAdapter",
    "JevConfiguration",
    "JevConfigurationError",
    "JevModelRouter",
    "JevModelRouterConfig",
    "JevResponseError",
    "JevRouterError",
    "JevRouterObserver",
    "JevRouterSettings",
    "JevRouterUnavailableError",
    "JevTransport",
    "JevSystemOneModelRouter",
    "TypeSafeModelRouter",
    "GroundedFollowUpModelAdapter",
    "MAX_FOLLOW_UP_RESPONSE_CHARS",
    "ModelResponseError",
    "OpenAICompatibleChatClient",
    "OpenAICompatibleChunkSummaryAdapter",
    "OpenAICompatibleCriticAdapter",
    "OpenAICompatibleEmbeddingAdapter",
    "OpenAICompatibleExecutorAdapter",
    "OpenAICompatibleModelAdapter",
    "OpenAICompatiblePlannerAdapter",
    "OpenAICompatibleRetrievalPlannerAdapter",
    "PlannerModelAdapter",
    "ProviderAuthenticationError",
    "ProviderConfig",
    "ProviderConfigurationError",
    "ProviderError",
    "ProviderHttpResponse",
    "ProviderRequestError",
    "ProviderResponseError",
    "ProviderTransportError",
    "ProviderTransientError",
    "RetrievalPlannerModelAdapter",
    "SYSTEM_POLICY",
    "StructuredResponseObserver",
    "STRUCTURED_RESPONSE_MAX_DIAGNOSTIC_BYTES",
    "STRUCTURED_RESPONSE_MAX_ERRORS",
    "STRUCTURED_RESPONSE_MAX_FIELDS",
    "StdlibAsyncJsonPostClient",
    "decode_embedding",
    "decode_structured_model",
    "decode_follow_up_answer",
    "post_json",
    "response_parts",
]
