"""Application import surface for the X2-A provenance contract."""

from dovideo.domain.provenance import (
    CHUNKING_CONTRACT_VERSION,
    EXTRACTION_CONTRACT_VERSION,
    MAX_EVIDENCE_SOURCE_ITEM_REFS,
    NORMALIZATION_VERSION,
    PROVENANCE_VERSION,
    SegmentIdentity,
    SourceItemIdentity,
    SourceRevision,
    SourceType,
    calculate_source_revision,
    canonical_frame_ref,
    canonical_source_observation_digest,
    canonical_source_observations,
    canonical_text,
    chunk_id_for,
    compute_source_revision,
    content_digest,
    segment_id_for,
    sha256_canonical,
    source_item_id_for,
)

__all__ = [
    "CHUNKING_CONTRACT_VERSION",
    "EXTRACTION_CONTRACT_VERSION",
    "MAX_EVIDENCE_SOURCE_ITEM_REFS",
    "NORMALIZATION_VERSION",
    "PROVENANCE_VERSION",
    "SegmentIdentity",
    "SourceItemIdentity",
    "SourceRevision",
    "SourceType",
    "calculate_source_revision",
    "canonical_frame_ref",
    "canonical_source_observation_digest",
    "canonical_source_observations",
    "canonical_text",
    "chunk_id_for",
    "compute_source_revision",
    "content_digest",
    "segment_id_for",
    "sha256_canonical",
    "source_item_id_for",
]
