"""Phase 1 immutable domain contracts for the DOVideo Python rewrite."""

from .agent import (
    MAX_PLAN_TASK_LENGTH,
    MAX_PLAN_TASKS,
    AgentPlan,
    AgentState,
    CriticResult,
    java_string_length,
)
from .analysis import AnalysisEvidence, AnalysisResult, AnalysisSection
from .feedback import AgentFeedback
from .follow_up import GroundedFollowUpAnswer, GroundedFollowUpEvidence
from .budget import (
    AgentBudgetConfig,
    AgentExecutionBudgetConfig,
    AgentUsage,
    BudgetUsage,
    ExecutionBudgetConfig,
)
from .modes import AnalysisMode, ModeProfile
from .provenance import (
    CHUNKING_CONTRACT_VERSION,
    EXTRACTION_CONTRACT_VERSION,
    MAX_EVIDENCE_SOURCE_ITEM_REFS,
    NORMALIZATION_VERSION,
    PROVENANCE_VERSION,
    SegmentIdentity,
    SourceItemIdentity,
    SourceRevision,
    SourceType,
    calculate_source_revision,
    canonical_frame_ref,
    canonical_source_observation_digest,
    canonical_source_observations,
    canonical_text,
    chunk_id_for,
    compute_source_revision,
    content_digest,
    segment_id_for,
    sha256_canonical,
    source_item_id_for,
)
from .tasks import TaskEvent, TaskStage, TaskStatus, TaskStatusState
from .video import (
    TemporalObservation,
    ChunkSummary,
    VideoChunk,
    VideoContext,
    VideoEvidenceHit,
    VideoRetrievalIntent,
    VideoSegment,
)

__all__ = [
    "AgentPlan",
    "AgentFeedback",
    "AgentState",
    "AgentBudgetConfig",
    "AgentExecutionBudgetConfig",
    "AgentUsage",
    "AnalysisEvidence",
    "AnalysisMode",
    "AnalysisResult",
    "AnalysisSection",
    "ChunkSummary",
    "CHUNKING_CONTRACT_VERSION",
    "CriticResult",
    "EXTRACTION_CONTRACT_VERSION",
    "BudgetUsage",
    "ExecutionBudgetConfig",
    "GroundedFollowUpAnswer",
    "GroundedFollowUpEvidence",
    "MAX_PLAN_TASK_LENGTH",
    "MAX_PLAN_TASKS",
    "MAX_EVIDENCE_SOURCE_ITEM_REFS",
    "ModeProfile",
    "NORMALIZATION_VERSION",
    "PROVENANCE_VERSION",
    "SegmentIdentity",
    "SourceItemIdentity",
    "SourceRevision",
    "SourceType",
    "TaskEvent",
    "TaskStage",
    "TaskStatus",
    "TaskStatusState",
    "VideoChunk",
    "VideoContext",
    "TemporalObservation",
    "VideoEvidenceHit",
    "VideoRetrievalIntent",
    "VideoSegment",
    "calculate_source_revision",
    "canonical_frame_ref",
    "canonical_source_observation_digest",
    "canonical_source_observations",
    "canonical_text",
    "chunk_id_for",
    "compute_source_revision",
    "content_digest",
    "java_string_length",
    "segment_id_for",
    "sha256_canonical",
    "source_item_id_for",
]
