"""Phase 8 durable checkpoint/media persistence adapters.

Only standard-library/injectable components live here.  MySQL/Redis adapters
remain driver-neutral and require an outer composition root to inject clients.
"""

from .cache import (
    DEFAULT_CHECKPOINT_TTL_SECONDS,
    InMemoryCheckpointCache,
    InMemoryHotCache,
    InMemoryHotCheckpointCache,
    MemoryCheckpointCache,
    MemoryHotCheckpointCache,
)
from .codec import (
    CheckpointSerializer,
    CheckpointVersion,
    JsonCheckpointCodec,
    VersionedJsonCheckpointCodec,
)
from .errors import (
    CheckpointCacheError,
    CheckpointCodecError,
    CheckpointDeserializeError,
    CheckpointDeserializationError,
    CheckpointDeleteError,
    CheckpointError,
    CheckpointReadError,
    CheckpointSerializationError,
    CheckpointVersionMismatchError,
    CheckpointWriteError,
    DurableCheckpointError,
    MediaDeleteError,
    MediaPersistenceError,
    MediaReadError,
    MediaRecordPersistenceError,
    MediaWriteError,
)
from .models import CheckpointRecord
from .ports import (
    CheckpointCache,
    CheckpointCodec,
    CheckpointStore,
    DurableCheckpointStore,
    HotCheckpointCache,
)
from .repository import AgentCheckpointRepository, CheckpointRepository
from .dead_letter_handoff import (
    CheckpointDeadLetterHandoffStore,
    DurableDeadLetterHandoffStore,
    PENDING_DEAD_LETTER_FIELD,
    RepositoryDeadLetterHandoffStore,
)
from .mysql_checkpoint import (
    DbApiMySqlCheckpointStore,
    MySQLCheckpointStore,
    MySQLDurableCheckpointStore,
    MySqlCheckpointStore,
    MySqlDurableCheckpointStore,
)
from .sqlalchemy import (
    Base as SqlAlchemyBase,
    CheckpointRow as SqlAlchemyCheckpointRow,
    FailedAnalysisTaskRow as SqlAlchemyFailedAnalysisTaskRow,
    FailedAnalysisTaskReplayRow as SqlAlchemyFailedAnalysisTaskReplayRow,
    AgentExecutionRecordRow as SqlAlchemyAgentExecutionRecordRow,
    AgentExecutionEventRow as SqlAlchemyAgentExecutionEventRow,
    FailedTaskRecord,
    FailedTaskReplayAttempt,
    FailedTaskReplayReservation,
    MediaRow as SqlAlchemyMediaRow,
    R2DatabaseError,
    SqlAlchemyCheckpointStore,
    MySQLExecutionRecordRepository,
    SqlAlchemyExecutionRecordRepository,
    SqlAlchemyFailedTaskStore,
    SqlAlchemyMediaRecordRepository,
    SqlAlchemyUserStore,
    UserRecord,
    UserRow as SqlAlchemyUserRow,
    create_schema,
    create_sqlalchemy_engine,
)
from .redis_cache import RedisCache, RedisCheckpointCache, RedisHotCheckpointCache
from .task_lifecycle import (
    CheckpointTaskLifecycleStore,
    DEFAULT_LIFECYCLE_MAX_ATTEMPTS,
    LIFECYCLE_CHECKPOINT_PREFIX,
    LIFECYCLE_FIELD,
    TaskLifecyclePersistenceError,
)
from .media_repository import (
    DbApiMySQLMediaRecordRepository,
    DbApiMySqlMediaRecordRepository,
    MySQLMediaRecordRepository,
    MySqlMediaRecordRepository,
    SQLiteMediaRecordRepository,
    SqliteMediaRecordRepository,
    SqliteMediaRepository,
)
from dovideo.application.checkpoint_service import (
    AgentCheckpointService,
    CheckpointService,
    RevisionCheckpoint,
)
from dovideo.application.errors import (
    AgentFeedbackPersistenceError,
    FeedbackPersistenceError,
)
from dovideo.domain import AgentFeedback
from .sqlite import (
    InMemoryCheckpointStore,
    InMemoryDurableCheckpointStore,
    SQLiteCheckpointStore,
    SQLiteDurableCheckpointStore,
    SqliteCheckpointStore,
    SqliteDurableCheckpointStore,
)

__all__ = [
    "AgentCheckpointRepository",
    "CheckpointDeadLetterHandoffStore",
    "DurableDeadLetterHandoffStore",
    "PENDING_DEAD_LETTER_FIELD",
    "RepositoryDeadLetterHandoffStore",
    "DbApiMySqlCheckpointStore",
    "MySQLCheckpointStore",
    "MySQLDurableCheckpointStore",
    "MySqlCheckpointStore",
    "MySqlDurableCheckpointStore",
    "SqlAlchemyBase",
    "SqlAlchemyCheckpointRow",
    "SqlAlchemyFailedAnalysisTaskRow",
    "SqlAlchemyFailedAnalysisTaskReplayRow",
    "SqlAlchemyAgentExecutionRecordRow",
    "SqlAlchemyAgentExecutionEventRow",
    "FailedTaskRecord",
    "FailedTaskReplayAttempt",
    "FailedTaskReplayReservation",
    "SqlAlchemyMediaRow",
    "R2DatabaseError",
    "SqlAlchemyCheckpointStore",
    "MySQLExecutionRecordRepository",
    "SqlAlchemyExecutionRecordRepository",
    "SqlAlchemyFailedTaskStore",
    "SqlAlchemyMediaRecordRepository",
    "SqlAlchemyUserStore",
    "UserRecord",
    "SqlAlchemyUserRow",
    "create_schema",
    "create_sqlalchemy_engine",
    "AgentCheckpointService",
    "AgentFeedback",
    "AgentFeedbackPersistenceError",
    "FeedbackPersistenceError",
    "RevisionCheckpoint",
    "CheckpointCacheError",
    "CheckpointCache",
    "CheckpointCodec",
    "CheckpointCodecError",
    "CheckpointDeserializeError",
    "CheckpointDeserializationError",
    "CheckpointDeleteError",
    "CheckpointError",
    "CheckpointRecord",
    "CheckpointReadError",
    "CheckpointRepository",
    "CheckpointService",
    "CheckpointSerializer",
    "CheckpointSerializationError",
    "CheckpointStore",
    "CheckpointVersion",
    "CheckpointVersionMismatchError",
    "CheckpointWriteError",
    "DEFAULT_CHECKPOINT_TTL_SECONDS",
    "DurableCheckpointError",
    "DurableCheckpointStore",
    "MediaDeleteError",
    "MediaPersistenceError",
    "MediaReadError",
    "MediaRecordPersistenceError",
    "MediaWriteError",
    "HotCheckpointCache",
    "InMemoryCheckpointCache",
    "InMemoryCheckpointStore",
    "InMemoryDurableCheckpointStore",
    "InMemoryHotCache",
    "InMemoryHotCheckpointCache",
    "JsonCheckpointCodec",
    "MemoryHotCheckpointCache",
    "MemoryCheckpointCache",
    "SQLiteCheckpointStore",
    "SQLiteDurableCheckpointStore",
    "SqliteCheckpointStore",
    "SqliteDurableCheckpointStore",
    "VersionedJsonCheckpointCodec",
    "RedisCache",
    "RedisCheckpointCache",
    "RedisHotCheckpointCache",
    "DbApiMySQLMediaRecordRepository",
    "DbApiMySqlMediaRecordRepository",
    "MySQLMediaRecordRepository",
    "MySqlMediaRecordRepository",
    "SQLiteMediaRecordRepository",
    "SqliteMediaRecordRepository",
    "SqliteMediaRepository",
    "CheckpointTaskLifecycleStore",
    "DEFAULT_LIFECYCLE_MAX_ATTEMPTS",
    "LIFECYCLE_CHECKPOINT_PREFIX",
    "LIFECYCLE_FIELD",
    "TaskLifecyclePersistenceError",
]
